pur_beurre/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from quality import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.accueil),
    path('quality/', include('quality.urls', namespace='quality')),


]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#
#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),
#
#     ] + urlpatterns

quality/urls.py
from . import views
from django.urls import path


app_name = "quality"

urlpatterns = [

    path('', views.accueil, name='accueil'),


    # connected views
    path('my_account/', views.myaccount, name='myaccount'),
    path('food/', views.food, name='food'),

    # unconnected views
    path('query_data/', views.query_data, name='query_data'),
    path('sub_product/', views.sub_product, name= 'sub_product'),
    path('user_choice/', views.user_choice, name='user_choice'),
    path('credits/', views.credits, name='credits'),

    # authentification view
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout/', views.logout_view, name='logout'),

]

quality/models.py
from django.conf import settings
from django.db import models
# Create your models here.

class TimestamptedModel(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)


    class Meta:
        abstract = True



class SelectedProduct(models.Model):
    name =  models.CharField(max_length=100)
    url = models.URLField()
    img = models.URLField()
    n_grade = models.CharField(max_length=1)
    category = models.CharField(max_length=150)

    class Meta:
        verbose_name = "selected_product"

    def __str__(self):
        return self.name


class Backup(TimestamptedModel):
    selected_product_id = models.ForeignKey(SelectedProduct, on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "backup"

    def __str__(self):
        return str(self.id)



class SubstitutProduct(models.Model):
    name =  models.CharField(max_length=250)
    url = models.URLField()
    img = models.URLField()
    n_grade = models.CharField(max_length=1)
    category = models.CharField(max_length=250)
    img_nutrition = models.URLField(default='0000000')
    store = models.CharField(max_length=250, default='0000000')
    backup_id = models.ForeignKey(Backup , on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    selected_product_id = models.ForeignKey(SelectedProduct, on_delete=models.CASCADE)


    class Meta:
        verbose_name = "substitut_product"

    def __str__(self):
        return self.name

quality/forms.py
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin



class CustomAuthenticationForm(AuthenticationForm):
    '''form to log an user using the django User model, this form is passed to the login view'''

    class Meta:
        model = User
        fields = ['username', 'password']


class CustomUserCreationForm(PopRequestMixin, CreateUpdateAjaxMixin,
                             UserCreationForm):
    '''form to create an user using the Django User model, this form is passed to the signup view.
    PopRequestMixin from bootstrap_modal_forms.mixins : pops request out of the kwargs and attaches it to the form's
    instance.
    CreateUpdateAjaxMixin : Mixin which passes or saves object based on request type.
    '''
    class Meta:
        model = User
        fields = ['username', 'email']

quality/views.py
# Create your views here.
from django.shortcuts import render, redirect
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.contrib.auth.views import LoginView
from  django.contrib.auth import logout
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from bootstrap_modal_forms.mixins import LoginAjaxMixin, PassRequestMixin
from .methods import query_off, best_substitut
from .models import SelectedProduct, SubstitutProduct, Backup
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login
from django.contrib import messages
import re

def accueil(request):
    return render(request, 'quality/index.html')

def credits(request):
    return render(request, 'quality/credits.html')

def query_data(request):
    ''' we retrieve the user input: 'query'
     we query the OFF API : 'query_off' methods.py
     and we display useful data '''

    query = request.GET.get('query', None)

    if not query:

        title = "saisissez un produit ! "
        context = {'title': title }
        return render(request, 'quality/index.html', context)
    else:
        # query_off function calls OFF API and return 6 products
        data = query_off(query)

        # in case of invalid user entry
        if not data:
            title = 'Votre recherche "{}" n \' a donné aucun resultat!'.format(query)
            context = {'title': title}
            return render(request , 'quality/index.html' , context)

        # in case of valid entry
        else:
            title = 'Votre recherche est :  "{}"'. format(query)
            context = {
                'title': title,
                'data': data
            }

    return render(request, 'quality/query_data.html', context)

def sub_product(request):
    '''recovery of the selected product
    recording data in the session
    category recovery
    interrogation of the OFF api and display of the 6 best substitute products: via best_substitute methods.py '''

    # get the user choice from the checkbox
    choices = request.GET.get('subscribe', None)

    # split the checkbox's return in order to make a python list
    choices = choices.split(', ')

    # record selected product in session
    record_session = ['selected_name', 'selected_category', 'selected_img', 'selected_nutriscore', 'selected_url']
    for value, choice in zip(record_session, choices):
        request.session[value] = choice

    cat = request.session['selected_category']

    # request to OpenFoodFact and return six best products with the same category
    data = best_substitut(cat)
    title = 'six produits meilleurs ont été trouvés dans la catégorie {}'.format(cat)
    context = {
        'title': title ,
        'data': data
    }
    return render(request, 'quality/sub_product.html', context)

@login_required
def user_choice(request):
    '''View showing the pair of products saved.
     Registers data in the database.
     The substitute product is recorded in the session for display.'''
    # get the user choice from the checkbox
    choices = request.GET.get('subscribe', None)

    # split the checkbox's return in order to make a python list
    choices = choices.split(', ')



    # record selected product in database
    p_selected = SelectedProduct.objects.create(
        name = request.session['selected_name'],
        url = request.session['selected_url'],
        img = request.session['selected_img'],
        n_grade = request.session['selected_nutriscore'],
        category = request.session['selected_category'])

    # record the backup with selected_product_id and user_id
    backup = Backup.objects.create(
        user_id = request.user,
        selected_product_id = p_selected
    )

    # record the substitute product with all the foreign key
    p_substitut = SubstitutProduct.objects.create(
        name = choices[0],
        category = choices[1],
        img = choices[2],
        n_grade = choices[3],
        url = choices[4],
        img_nutrition = choices[5],
        store = choices[6],

        backup_id = backup,
        user_id = request.user,
        selected_product_id = p_selected
    )

    # record selected product in session just for display
    record_session = ['substitut_name', 'substitut_category', 'substitut_img', 'substitut_nutriscore', 'substitut_url']
    for value , choice in zip(record_session, choices):
        request.session[value] = choice
    return render(request, 'quality/user_choice.html')




@login_required
def myaccount(request):
    return render(request, 'quality/account.html')

@login_required
def food(request):
    '''View which display page of Aliments . firstly we are looking for the connected user,
    then we are looking for all backups related to this user, the display supports pagination'''

    # define the connected user
    user = request.user

    # request inner join on selectedproduct/Backup/substitutproduct
    sel_product_list = SelectedProduct.objects.filter(backup__user_id=user.id, substitutproduct__user_id=user.id).order_by('id')
    sub_product_list = SubstitutProduct.objects.filter(user_id=user.id).order_by('id')
    # Slice pages
    paginator0 = Paginator(sel_product_list, 1)
    paginator1 = Paginator(sub_product_list, 1)
    # Get current page
    page = request.GET.get('page', 1)
    try:
        # return only the first product and not the others
        sel_products = paginator0.page(page)
        sub_products = paginator1.page(page)

    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        sel_products = paginator0.page(1)
        sub_products = paginator1.page(1)
    except EmptyPage:
        # If page out of range (e.g 99999), deliver last page of results.
        sel_products = paginator0.page(paginator0.num_pages)
        sub_products = paginator1.page(paginator1.num_pages)
    context = {
        'sel_products': sel_products,
        'sub_products': sub_products
    }

    return render(request, 'quality/food.html', context)



# Authentification views

class CustomLoginView(LoginAjaxMixin, SuccessMessageMixin, LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'quality/registration/login.html'
    success_message = 'Vous etes à présent connecté'

class SignUpView(PassRequestMixin, SuccessMessageMixin, generic.CreateView):
    form_class = CustomUserCreationForm
    template_name = 'quality/registration/signup.html'

    def get_success_url(self):
        # log user after register
        username = self.request.POST['username']
        password = self.request.POST['password1']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
            referer_url = self.request.META.get('HTTP_REFERER')
            messages.success(self.request, ('Création de compte réussie ! Vous etes à présent connecté !'))
            return referer_url


def logout_view(request):
    logout(request)
    messages.success(request, ('Vous etes déconnecté'))
    return redirect('quality:accueil')

quality/templates/quality/account.html
{% extends 'quality/base.html' %}
{% load static %}

{% block content %}

<header class="masthead text-center d-flex">
   <div class="container my-auto">
      <div class="row">
         <div class="col-lg-12 mx-auto pt-3 custom-color">
            <h5 class="text-uppercase">Bonjour ! </h5>
             <hr>
            <h4>Votre nom d'utilisateur : <strong>{{user.username}}</strong> </h4>
             <hr>
             <h4 > Votre mail : <strong>{{user.email}}</strong> </h4>
            <hr>
         </div>
      </div>
   </div>
</header>

{% endblock %}

quality/templates/quality/base.html
<!DOCTYPE html>
<html lang="fr">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      {% load static %}
      <title>Pur Beurre </title>
      <!-- Bootstrap core CSS -->
      <link href="{% static 'quality/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom fonts for this template -->
      <link href= '{% static "quality/vendor/fontawesome-free/css/all.min.css" %}' rel="stylesheet" type="text/css">
      <link href= '{% static "quality/vendor/fontawesome-free/css/brands.min.css" %}' rel="stylesheet" type="text/css">
      <link href= '{% static "quality/vendor/fontawesome-free/webfonts/fa-brands-400.svg" %}' rel="stylesheet" type="text/css">
      <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
      <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
      <!-- Plugin CSS -->
      <link href='{% static "quality/vendor/magnific-popup/magnific-popup.css"%}' rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href= '{% static "quality/css/creative.min.css" %}' rel="stylesheet">
      <link href="{% static 'quality/css/main.css' %}" rel="stylesheet">
   </head>
   <body id="page-top">
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav" >
         <div class="container">
            <a id='brand-name' class="navbar-brand js-scroll-trigger" href="{% url 'quality:accueil' %}"><img alt = "logo" src="{% static 'quality/img/logo_pur_beurre.png' %}" class="logo-navbar"/>Pur Beurre</a>
            <!--display colunm menu on small device -->
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
               <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                     <!--formulaire de recherche-->
                     <form class="nav-link" action="{% url 'quality:query_data' %}" method="get" accept-charset="utf-8">
                        <input type="text" name="query" id ="query">
                        <input type="submit" class="btn btn-outline-success my-2 my-sm-0" value="Chercher">
                     </form>
                  </li>
                  {% block nav-style %}{% endblock %}
                  {% if user.is_authenticated %}
                  {% include "quality/navbar_connected.html" %}
                  {% else %}
                  <li class="nav-item">
                     <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                  </li>
                  <!--Trigger element for Sign-up modal-->
                  <li class="nav-item">
                     <i class="nav-link signup-btn fas fa-user-plus fa-2x mb-3" data-toggle="tooltip" title="Creer un compte" ></i>
                  </li>
                  <!--Connexion Trigger element for Login modal-->
                  <li class= "nav-item">
                     <i class="nav-link login-btn fas fa-sign-in-alt fa-2x mb-3" data-toggle="tooltip" title="Connexion" ></i>
                  </li>
                  {% endif %}
               </ul>
            </div>
         </div>
      </nav>
      <!--Modal markup placement login-->
      <div class="modal fade" tabindex="-1" role="dialog" id="modal">
         <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
         </div>
      </div>
      {% block content %}{% endblock %}
      <section class="bg-contact" id="contact">
         <div class="container">
            <div class="row">
               <div class="col-lg-8 mx-auto text-center">
                  <h2 class="section-heading">Contactez-nous!</h2>
                  <hr class="my-4">
                  <p class="mb-5">Vous etes enthousiasmés par notre idée de Plateforme et désirez nous soutenir dans notre initiative de mieux manger pour mieux vivre ? C'est avec grand plasir que nous accueillons vos idées et vos compliments!</p>
               </div>
            </div>
            <div class="row">
               <div class="col-lg-4 ml-auto text-center">
                  <i class="fas fa-phone fa-3x mb-3 text-icone sr-contact-1"></i>
                  <p>09-57-88-47-90</p>
               </div>
               <div class="col-lg-4 mr-auto text-center">
                  <i class="fas fa-envelope fa-3x mb-3 text-icone sr-contact-2"></i>
                  <p>
                     <a href="mailto:your-email@your-domain.com" style="text-decoration: none">pur-beurre@resto.com</a>
                  </p>
               </div>
            </div>
         </div>
      </section>
      <section class="bg-footer">
         <div class="container">
            <div class="row">
               <div class="col-lg-4 col-md-6 text-center">
                  <div class="service-box mt-5 mx-auto">
                     <i class="fas fa-4x fa-gem text-icone mb-3 sr-icon-1" ></i>
                     <a href ="{% url 'quality:credits' %}" class="mb-3 a-headings">Mentions légales</a>
                     <p class="text-muted mb-0">Nous citons les sources de notre inspiration.</p>
                  </div>
               </div>
               <div class="col-lg-4 col-md-6 text-center">
                  <div class="service-box mt-5 mx-auto">
                     <i class="fas fa-4x fa-paper-plane text-icone mb-3 sr-icon-2"></i>
                     <a href="#contact" class="mb-3 a-headings js-scroll-trigger">Contact</a>
                     <p class="text-muted mb-0">Nous serons heureux d'échanger avec vous !</p>
                  </div>
               </div>
               <div class="col-lg-4 col-md-6 text-center">
                  <div class="service-box mt-5 mx-auto">
                     <i class="fas fa-4x fa-gift text-icone mb-3 sr-icon-3"></i>
                     <a href="https://github.com/horlas/OC_Project8" target="_blank" class="mb-3 a-headings">Code Pur-beurre</a>
                     <p class="text-muted mb-0">Pour les développeurs, les correcteurs et les curieux !</p>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-lg-12 col-md-6 text-center mt-5">
                  <h6 class="custom_title" style="font-family:'Scope One'"><strong>Aurélia Gourbère novembre 2018 - Projet 8 Parcours python - Openclassrooms</strong></h6>
               </div>
            </div>
         </div>
      </section>
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'quality/vendor/jquery/jquery.min.js'%}"></script>
      <script src="{% static 'quality/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <!-- Plugin JavaScript -->
      <script src="{% static 'quality/vendor/jquery-easing/jquery.easing.min.js'%}"></script>
      <script src="{% static 'quality/vendor/scrollreveal/scrollreveal.min.js'%}"></script>
      <script src="{% static 'quality/vendor/magnific-popup/jquery.magnific-popup.min.js'%}"></script>
      <!-- Custom scripts for this template -->
      <script src="{% static 'quality/js/creative.min.js'%}"></script>
      <!--Customs script for the project -->
      <script src="{% static 'quality/js/jquery.bootstrap.modal.forms.min.js' %}"></script>
      <!-- Open login modal -->
      <script type="text/javascript">
         $(function () {
         // Log in button
         $(".login-btn").modalForm({formURL: "{% url 'quality:login' %}"});
         });
      </script>
      <!-- Open sign-up modal-->
      <script type="text/javascript">
         $(function () {
         // Sign up button
         $(".signup-btn").modalForm({formURL: "{% url 'quality:signup' %}"});
         });
      </script>
      <script>
         $(document).ready(function(){
             $('[data-toggle="tooltip"]').tooltip();
         });
      </script>
      {% block javascript %}{% endblock %}
   </body>
</html>

quality/templates/quality/credits.html
{% extends 'quality/base.html' %}
{% load static %}

{% block content %}

<header class="masthead text-center d-flex">
   <div class="container my-auto">
      <div class="row">
         <div class="col-lg-10 mx-auto pt-3 custom-color">
            <h5 class="text-uppercase">Mentions légales </h5>
             <hr>
             <h6 > Powered by : <a href="https://www.djangoproject.com/" target="_blank">Django</a></h6>
             <hr>
            <h6>Template Bootstrap  <a href="https://blackrockdigital.github.io/startbootstrap-creative/" target="_blank">Bootstrap</a></h6>
             <hr>
            <h6>Logo  <a href="https://company-82435.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide#/elements-basiques/marque-et-logo" target="_blank">Pur-Beurre Openclassrooms</a></h6>
             <hr>
            <h6>Icone  <a href="https://thenounproject.com/term/carrot/29691/" target="_blank">The Noun Project</a></h6>
             <hr>
             <h6>Photo  <a href="https://unsplash.com/photos/k60JspcBwKE" target="_blank">Kawin Harasai</a></h6>
             <hr>
             <h6>Portofolio  <a href="https://www.pixar.com/feature-films/ratatouille/#rat-main" target="_blank">Pixar Ratatouille</a></h6>
             <hr>

         </div>
      </div>
   </div>
</header>

{% endblock %}

quality/templates/quality/display_messages.html
<!-- To display success login/logout message -->
{% if messages %}
   {% for message in messages %}
    <p class ='custom-color mt-5'>{{ message }}</p>
    {% endfor %}
{% endif %}

quality/templates/quality/navbar_connected.html
{% load static %}

{% block nav-style %}

            <li class= "nav-item">
                <a href="{% url 'quality:myaccount' %}"><i class="nav-link fas fa-user fa-2x mb-3" data-toggle="tooltip" title="Mon Compte" ></i></a>
            </li>

            <li class="nav-item">
                <a href="{% url 'quality:food' %}"><i class="nav-link icon-noun_Carrot_29691 fa-3x mb-3 " data-toggle="tooltip" title="Aliments/Sauvegardes"></i></a>
            </li>

            <!--Deconnexion-->
            <li class= "nav-item">
                <a href="{% url 'quality:logout' %}"><i class="nav-link fas fa-sign-out-alt fa-2x mb-3" data-toggle="tooltip" title="Deconnexion"></i></a>

            </li>

{% endblock %}

quality/templates/quality/query_data.html
{% extends 'quality/base.html' %}
{% load static %}

{% block content %}

<header class="nav_masthead ">
   <div class="container my-auto">
      <div class="row row-centered">
         <div class="col-lg-6 col-md-5 col-sm-4 mx-auto ">
             {% include 'quality/display_messages.html' %}

<h4 class="text-uppercase custom-color p-4 mt-3" >
               <strong>{{title}}</strong>
            </h4>
         </div>
      </div>
   </div>

</header>
<section id='choice' class="bg-footer p-4 text-center" >
   <div  class="container my-auto">

      <h3 class="custom_title pb-3"> Choisissez le produit pour lequel vous voulez un substituant : </h3>
      <div class="row">
         {% for dict_item in data %}
         <div class="col-xl-4 px-xl-5 col-lg-4 col-md-5 col-sm-6 col-xs-10 mx-auto text-center">
            <form action="{% url 'quality:sub_product' %}" method="GET">
               <div class="item">

                  <span class="notify-badge good-product" >{{dict_item.nutriscore}}</span>
                  <img class="product_img img-fluid rounded"  src="{{dict_item.img}}" alt="{{dict_item.product_name}}" >

               </div>
               <div class="carousel-caption mb-5 ">
                  <h5 class="custom-color ">{{dict_item.product_name}}</h5>
               </div>
               <button type="submit" class="btn btn-outline-light text-icone mt-3 "name="subscribe" value="{{dict_item.product_name}}, {{dict_item.category}}, {{dict_item.img}}, {{dict_item.nutriscore}}, {{dict_item.url}}">
               <i class="fas fa-utensils fa-2x text-icone sr-save-1 "></i>
               Selectionner
               </button>
            </form>
         </div>
         {% endfor %}
      </div>
   </div>
</section>

{% endblock %}

quality/templates/quality/search_product.html
<hr>
<p class="font-weight-bold  mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</p>
<div class="col-lg-8 mx-auto">
   <form action="{% url 'quality:query_data' %}" method="get" accept-charset="utf-8">
      <input type="text" name="query" id ="query">
      <input type="submit" class="btn btn-primary btn-xl" value="Chercher">
   </form>
   <hr>
    <!-- To display invalid user entries-->
   <h2 class="custom-color">
      <strong>{{title}}</strong>
   </h2>
</div>

quality/templates/quality/sub_product.html
{% extends 'quality/base.html' %}
{% load static %}
{% block content %}
<header class="nav_masthead">
</header>
<section id='selected-product' class="product p-4" >
   <div class="container my-auto">
      <div class="row row-centered">
         <div class="col-lg-3 col-md-5 col-sm-4 mx-auto ">
             {% include 'quality/display_messages.html' %}
            <div class="item">
               <a href="#">
               <span class="notify-badge bg-primary" >{{request.session.selected_nutriscore}}</span>
               <img class="product_img img-fluid rounded"  src="{{request.session.selected_img}}" alt="{{request.session.selected_name}}" >
               </a>
            </div>
            <div class="carousel-caption  ">
               <h5 class=" custom-color" >{{request.session.selected_name}}</h5>
            </div>
         </div>
      </div>
   </div>
</section>
<section id='choice' class="bg-footer p-4 text-center" >
   <div  class="container my-auto">
      {% if user.is_authenticated %}
      <h3 class="custom_title pb-3"> Vous pouvez remplacer ce produit par : </h3>
      <div class="row">
         {% for dict_item in data %}
         <div class="col-xl-4 px-xl-5 col-lg-4 col-md-5 col-sm-6 col-xs-10 mx-auto text-center">
            <form action="{% url 'quality:user_choice' %}" method="GET">
               <div class="item">

                  <span class="notify-badge good-product" >{{dict_item.nutriscore}}</span>
                  <img class="product_img img-fluid rounded"  src="{{dict_item.img}}" alt="{{dict_item.product_name}}" >

               </div>
               <div class="carousel-caption mb-5 ">
                  <h5 class="custom-color ">{{dict_item.product_name}}</h5>
               </div>
               <button type="submit" class="btn btn-outline-light text-icone mt-3 " name="subscribe"
                       value="{{dict_item.product_name}}, {{dict_item.category}}, {{dict_item.img}}, {{dict_item.nutriscore}}, {{dict_item.url}}, {{dict_item.img_nutrition}}, {{dict_item.magasins}}">
               <i class="fas fa-save fa-2x text-icone sr-save-1 "></i>
               Sauvegarder
               </button>
            </form>
         </div>
         {% endfor %}
      </div>
   </div>
   {% else %}
   <div class="row">
      <div class="col-lg-8 mx-auto text-center">
         <h2 class="section-heading"> Changez vos habitudes ! <br> Sauvegardez votre recherche !</h2>
         <hr class="my-4">
         <p class="mb-5">Vous pourrez ainsi retrouver tous vos produits de meilleure qualité et faire évoluer vos habitudes de consommation !
            Pour cela connectez vous ou créez un compte  ! Retrouvez toutes vos recherches dans la page aliment.
         </p>
         <div class="d-lg-inline d-sm-flex">
            <button class="signup-btn btn btn-primary" type="button" name="button1">Créer un compte</button>
            <button class="login-btn btn btn-primary" type="button" name="button">Se connecter</button>
         </div>
         <hr class="my-4">
      </div>
   </div>
   <div class="row">
      {% for dict_item in data %}
      <div class="col-xl-4 px-xl-5 col-lg-4 col-md-5 col-sm-6 col-xs-10 mx-auto text-center">
         <form action="#" >
            <div class="item">

               <span class="notify-badge good-product" >{{dict_item.nutriscore}}</span>
               <img class="product_img img-fluid rounded"  src="{{dict_item.img}}" alt="{{dict_item.product_name}}" >

            </div>
            <div class="carousel-caption mb-2 ">
               <h5 class="custom-color ">{{dict_item.product_name}}</h5>
            </div>
         </form>
      </div>
      {% endfor %}
   </div>
   {% endif %}
   </div>
   </div>
</section>
{% endblock %}